on: release
name: Build
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: yaronius/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: linux
          GO111MODULE: on
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: yaronius/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: linux
          GO111MODULE: on
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: yaronius/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: "386"
          GOOS: darwin
          GO111MODULE: on
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: yaronius/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: darwin
          GO111MODULE: on
